import Head from 'next/head'
import HomeContainer from '../containers/home'
export default function Home() {
  return (
    <div >
      <Head>
        <title>Github API - Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeContainer />
    </div>
  )
}
